version: '3.8'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=Seriophile123456
        - ACCEPT_EULA=Y
      restart: always
      expose:   #exposing ports internally
        - "1433"
      ports:
        - "1433:1433"
      volumes:
        - mssqlsystem:/var/opt/mssql/
        - mssqldata:/var/opt/sqlserver/data
        - mssqllog:/var/opt/sqlserver/log
        - mssqlbackup:/var/opt/sqlserver/backup  
  
    identityserver:
        container_name: identity-server
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=Seriophile123456;TrustServerCertificate=true;"
        depends_on:
          - mssql
        expose:
          - "4000"
        ports:
          - "4000:80"
          
    frontendserver:
      container_name: angular-server
      expose:
        - "4200"    
      ports:
        - "3333:80"
        - "3334:443"
        - "22:4200"
      volumes:
          - ./nginx-config:/etc/nginx/conf.d
      
    

networks:
  internal_network:
    driver: bridge
    