version: '3.8'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
      restart: always
      ports:
        - "1433:1433"
      volumes:
        - mssqldata:/var/opt/mssql/data
  
    identityserver:
        container_name: identityserver
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=true;"
        depends_on:
          - mssql
        ports:
          - "4000:80"
