version: '3.8'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
      restart: always
      expose:   #exposing ports internally
        - "1433"
      ports:
        - "1433:1433"
      volumes:
        - mssqldata:/var/opt/mssql/data
  
    identity-server:
        container_name: identity-server
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=true;"
        depends_on:
          - mssql
        expose:
          - "80"
        ports:
          - "4000:80"
          
    angular-server:
      container_name: angular-server   
      ports:
        - "3333:80"
        - "3334:443"
        - "22:4200"
      volumes:
          - ./nginx-config:/etc/nginx/conf.d
      
    

networks:
  internal_network:
    driver: bridge
  febe_network:
    driver: bridge
    