version: '3.4'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=admin123456
        - ACCEPT_EULA=Y
      restart: always
      ports:
        - "1433:1433"
      # Added due to error, no permission for creating /var/opt/mssql/data. Should be removed, and tested
      user: root
      volumes:
        - mssql_data:/var/opt/mssql/data
  
    identityserver:
      container_name: identity-server
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;"
      depends_on:
        - mssql
      ports:
        - "4000:80"  