version: '3.8'

services:
  
  mssql:
   #image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: .
      dockerfile: Mssql-Dockerfile
    
  
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  mongodb:
    image: mongo

  tvshow.api:
    image: ${DOCKER_REGISTRY-}tvshowapi
    build:
      context: .
      dockerfile: Services/Series/Series.API/Dockerfile

volumes:
  mssqlsystem:
  mssqldata:
  mssqllog:
  mssqlbackup:
  mongo_data:
  tvshow_data: