version: '3.8'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=Seriophile123456
        - ACCEPT_EULA=Y
      restart: always
      ports:
        - "1434:1433"
      volumes:
        - mssqlsystem:/var/opt/mssql/
        - mssqldata:/var/opt/sqlserver/data
        - mssqllog:/var/opt/sqlserver/log
        - mssqlbackup:/var/opt/sqlserver/backup  
  
    identityserver:
        container_name: identity-server
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=Seriophile123456;TrustServerCertificate=true;"
        depends_on:
          - mssql
        ports:
          - "4000:80"
    
    mongodb:
        container_name: mongodb
        restart: always
        ports:
          - "27017:27017"
        volumes:
          - mongo_data:/data/db

    tvshow.api:
        container_name: tvshow.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
        restart: always
        depends_on:
          - mongodb
        ports:
          - "8000:80"
