version: '3.8'

services:
    mssql:
      container_name: mssql
      environment:
        - SA_PASSWORD=MATF12345678rs2
        - ACCEPT_EULA=Y
      restart: always
      expose:   #exposing ports internally
        - "1433"
      ports:
        - "1434:1433"
      volumes:
        - mssqldata:/var/opt/mssql/data
  
    identity-server:
        container_name: identity-server
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=true;"
        depends_on:
          - mssql
        expose:
          - "80"
        ports:
          - "4000:80"

    
    mongodb:
        container_name: mongodb
        restart: always
        ports:
          - "27017:27017"
        volumes:
          - mongo_data:/data/db

    tvshow.api:
        container_name: tvshow.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
        restart: always
        depends_on:
          - mongodb
        ports:
          - "8000:80"

          
    angular-server:
      container_name: angular-server 
      restart: always
      ports:
        - "3333:80"
      volumes:
          - ./nginx-config:/etc/nginx/conf.d
      
      
    series-db:
      restart: always
      environment:
        POSTGRES_PASSWORD: "SecretPassword123$"  
      
    series-data:
      container_name: series-data
      restart: always
      ports:
        - "5090:80"
      environment:
         - "ConnectionStrings:DefaultConnection=Server=mssql;User Id=postgres;Password=SecretPassword123$;TrustServerCertificate=true;"
          
    adminer:
      container_name: adminer
      restart: always
      ports:
        - 8080:8080
      volumes:
        - postgres_data:/var/lib/postgresql/data

networks:
  internal_network:
    driver: bridge
  febe_network:
    driver: bridge
  series_network:
    driver: bridge
    